export const festivities: EventObject[] = [
  // 2025
  { startDate: '2025-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2025-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2025-01-22', title: 'Festivo: San Vicente Mártir', category: 'yearly' },
  { startDate: '2025-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2025-04-18', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2025-04-21', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2025-04-28', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2025-05-01', title: 'Festivo: Día del Trabajo', category: 'yearly' },
  { startDate: '2025-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2025-10-09', title: 'Festivo: Día de la Comunitat Valenciana', category: 'yearly' },
  { startDate: '2025-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2025-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2025-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },
  { startDate: '2025-12-25', title: 'Festivo: Navidad', category: 'yearly' },

  // 2024
  { startDate: '2024-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2024-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2024-01-22', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2024-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2024-03-29', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2024-04-01', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2024-04-08', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2024-05-01', title: 'Festivo: Día del Trabajo', category: 'yearly' },
  { startDate: '2024-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2024-10-09', title: 'Festivo: Día de la Comunidad Valenciana', category: 'yearly' },
  { startDate: '2024-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2024-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2024-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2024-12-25', title: 'Festivo: Navidad', category: 'yearly' },

  // 2023
  { startDate: '2023-01-06', title: 'Festivo: Día de Reyes', category: 'yearly' },
  { startDate: '2023-04-07', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2023-04-10', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2023-04-17', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2023-04-24', title: 'Festivo: (Se traslada) San Vicente Mártir', category: 'yearly' },
  { startDate: '2023-05-01', title: 'Festivo: Día Del Trabajo', category: 'yearly' },
  { startDate: '2023-06-24', title: 'Festivo: San juan', category: 'yearly' },
  { startDate: '2023-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2023-10-09', title: 'Festivo: Día de la Comunidad Valenciana', category: 'yearly' },
  { startDate: '2023-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2023-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2023-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2023-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },
  { startDate: '2023-12-25', title: 'Festivo: Navidad', category: 'yearly' },

  // 2022
  { startDate: '2022-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2022-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2022-01-22', title: 'Festivo: San Vicente Mártir', category: 'yearly' },
  { startDate: '2022-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2022-04-14', title: 'Festivo: Jueves Santo', category: 'yearly' },
  { startDate: '2022-04-15', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2022-04-18', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2022-04-25', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2022-06-24', title: 'Festivo: San Juan', category: 'yearly' },
  { startDate: '2022-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2022-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2022-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2022-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2022-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },

  // 2021
  { startDate: '2021-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2021-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2021-01-22', title: 'Festivo: San Vicente Mártir', category: 'yearly' },
  { startDate: '2021-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2021-04-02', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2021-04-05', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2021-04-12', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2021-05-01', title: 'Festivo: Fiesta del Trabajo', category: 'yearly' },
  { startDate: '2021-10-09', title: 'Festivo: Día de la Comunidad Valenciana', category: 'yearly' },
  { startDate: '2021-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2021-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2021-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2021-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },
  { startDate: '2021-12-25', title: 'Festivo: Navidad', category: 'yearly' },

  // 2020
  { startDate: '2020-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2020-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2020-01-22', title: 'Festivo: San Vicente Martir', category: 'yearly' },
  { startDate: '2020-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2020-04-10', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2020-04-13', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2020-04-20', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2020-05-01', title: 'Festivo: Fiesta del Trabajo', category: 'yearly' },
  { startDate: '2020-06-24', title: 'Festivo: San Juan', category: 'yearly' },
  { startDate: '2020-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2020-10-09', title: 'Festivo: Día de la Comunidad Valenciana', category: 'yearly' },
  { startDate: '2020-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2020-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },
  { startDate: '2020-12-25', title: 'Festivo: Navidad del Señor', category: 'yearly' },

  // 2019
  { startDate: '2019-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2019-01-22', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2019-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2019-04-19', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2019-04-22', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2019-04-29', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2019-05-01', title: 'Festivo: Fiesta del Trabajo', category: 'yearly' },
  { startDate: '2019-06-24', title: 'Festivo: San Juan', category: 'yearly' },
  { startDate: '2019-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2019-10-09', title: 'Festivo: Día de la Comunitat Valenciana', category: 'yearly' },
  { startDate: '2019-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2019-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2019-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2019-12-25', title: 'Festivo: Natividad del Señor', category: 'yearly' },

  // 2018
  { startDate: '2018-01-01', title: 'Festivo: Año nuevo', category: 'yearly' },
  { startDate: '2018-01-06', title: 'Festivo: Epifanía del Señor', category: 'yearly' },
  { startDate: '2018-01-22', title: 'Festivo: San Vicente Mártir', category: 'yearly' },
  { startDate: '2018-03-19', title: 'Festivo: San José', category: 'yearly' },
  { startDate: '2018-03-30', title: 'Festivo: Viernes Santo', category: 'yearly' },
  { startDate: '2018-04-02', title: 'Festivo: Lunes de Pascua', category: 'yearly' },
  { startDate: '2018-04-09', title: 'Festivo: San Vicente Ferrer', category: 'yearly' },
  { startDate: '2018-05-01', title: 'Festivo: Fiesta del Trabajo', category: 'yearly' },
  { startDate: '2018-08-15', title: 'Festivo: Asunción de la Virgen', category: 'yearly' },
  { startDate: '2018-10-09', title: 'Festivo: Día de la Comunidad Valenciana', category: 'yearly' },
  { startDate: '2018-10-12', title: 'Festivo: Fiesta Nacional Española', category: 'yearly' },
  { startDate: '2018-11-01', title: 'Festivo: Día de Todos los Santos', category: 'yearly' },
  { startDate: '2018-12-06', title: 'Festivo: Día de la Constitución Española', category: 'yearly' },
  { startDate: '2018-12-08', title: 'Festivo: Inmaculada Concepción', category: 'yearly' },
  { startDate: '2018-12-25', title: 'Festivo: Navidad', category: 'yearly' },
]
